#' Generate Full Poverty and Inequality Report in Excel
#'
#' Exports an Excel report that summarizes poverty measures, poverty distribution,
#' poverty composition, transfer simulation results, inequality indices, Lorenz curves,
#' and population distribution. The report includes tables and plots in separate sheets,
#' with an interactive table of contents.
#'
#' @param summary_list A named list of poverty summary outputs generated by `poverty_summary()`.
#' It must include the following elements:
#' \itemize{
#'   \item \code{poverty_measures}, \code{poverty_distribution}, \code{poverty_composition} (data.frames)
#'   \item \code{poverty_measures_plot}, \code{poverty_distribution_plot}, \code{poverty_composition_plot} (ggplot objects)
#' }
#' @param transfer_results A list returned by `transfers_summary()`, containing:
#' \itemize{
#'   \item \code{table}: data.frame of results
#'   \item \code{plot_efficiency}: ggplot object of scenario efficiency
#' }
#' @param inequality_df A data.frame of inequality indices returned by `inequality_indices()`
#' @param lorenz_plots A named list of ggplot Lorenz curves returned by `inequality_curve()`
#' @param population A ggplot object showing population distribution by group (output of `population_distribution()`)
#' @param file Path to the Excel file to generate (default is "poverty_summary_report.xlsx")
#'
#' @return No return value. A formatted Excel file is written to disk with multiple sheets.
#'
#' @importFrom openxlsx createWorkbook addWorksheet writeData writeDataTable addStyle insertImage writeFormula saveWorkbook makeHyperlinkString
#' @importFrom ggplot2 ggsave
#'
#' @export

full_generate_report <- function(summary_list,
                                 transfer_results = NULL,
                                 inequality_df = NULL,
                                 lorenz_plots = NULL,
                                 population = NULL,
                                 file = "poverty_summary_report.xlsx") {

  if (!requireNamespace("openxlsx", quietly = TRUE)) {
    stop("Package 'openxlsx' is required but not installed. Please install it.")
  }
  if (!requireNamespace("ggplot2", quietly = TRUE)) {
    stop("Package 'ggplot2' is required but not installed. Please install it.")
  }

  wb <- openxlsx::createWorkbook()

  addWorksheet(wb, "Table_of_Contents")
  toc <- data.frame(Title = character(), Sheet = character())
  add_toc <- function(title, sheet) {
    toc <<- rbind(toc, data.frame(Title = title, Sheet = sheet))
  }

  if (!is.null(population)) {
    openxlsx::addWorksheet(wb, "Population_Distribution")
    openxlsx::writeData(wb, "Population_Distribution", "Population Structure by Group", startRow = 1, startCol = 1)
    openxlsx::addStyle(wb, "Population_Distribution",
                       openxlsx::createStyle(textDecoration = "bold", fontSize = 14),
                       rows = 1, cols = 1)

    tmp <- tempfile(fileext = ".png")
    ggplot2::ggsave(tmp, population, width = 8, height = 5)
    openxlsx::insertImage(wb, "Population_Distribution", file = tmp, startRow = 3, startCol = 1, width = 8, height = 5, units = "in")

    add_toc("Population Distribution", "Population_Distribution")
  }

  add_table_sheet <- function(sheet_name, data, title) {
    openxlsx::addWorksheet(wb, sheet_name)
    openxlsx::writeData(wb, sheet = sheet_name, x = title, startRow = 1, startCol = 1)
    openxlsx::addStyle(wb, sheet_name,
                       openxlsx::createStyle(textDecoration = "bold", fontSize = 14),
                       rows = 1, cols = 1)
    openxlsx::writeDataTable(wb, sheet = sheet_name, x = data, startRow = 3, withFilter = TRUE)
    add_toc(title, sheet_name)
  }

  add_plot_sheet <- function(sheet_name, plot_obj, title) {
    openxlsx::addWorksheet(wb, sheet_name)
    openxlsx::writeData(wb, sheet = sheet_name, x = title, startRow = 1, startCol = 1)
    openxlsx::addStyle(wb, sheet_name,
                       openxlsx::createStyle(textDecoration = "bold", fontSize = 14),
                       rows = 1, cols = 1)
    tmp <- tempfile(fileext = ".png")
    ggplot2::ggsave(tmp, plot_obj, width = 8, height = 5)
    openxlsx::insertImage(wb, sheet = sheet_name, file = tmp, startRow = 3, startCol = 1, width = 8, height = 5, units = "in")
    add_toc(title, sheet_name)
  }

  add_table_sheet("Poverty_Measures", summary_list$poverty_measures, "FGT Poverty Measures by Group")
  add_table_sheet("Poverty_Distribution", summary_list$poverty_distribution, "Poverty Distribution")
  add_table_sheet("Poverty_Composition", summary_list$poverty_composition, "Contribution to National Poverty")

  if (!is.null(summary_list$poverty_measures_plot)) {
    add_plot_sheet("Plot_Measures", summary_list$poverty_measures_plot, "Poverty Measures - Plot")
  }
  if (!is.null(summary_list$poverty_distribution_plot)) {
    add_plot_sheet("Plot_Distribution", summary_list$poverty_distribution_plot, "Poverty Distribution - Plot")
  }
  if (!is.null(summary_list$poverty_composition_plot)) {
    add_plot_sheet("Plot_Composition", summary_list$poverty_composition_plot, "Poverty Composition - Plot")
  }

  if (!is.null(summary_list$poverty_measures)) {
    indicators <- c("headcount", "gap", "severity")
    plots <- lapply(indicators, function(ind) plot_poverty_measures(summary_list$poverty_measures, indicator = ind))
    openxlsx::addWorksheet(wb, "Plot_Measures_All")
    for (i in seq_along(plots)) {
      tmp <- tempfile(fileext = ".png")
      ggplot2::ggsave(tmp, plots[[i]], width = 8, height = 5)
      openxlsx::insertImage(wb, "Plot_Measures_All", file = tmp, startRow = 1 + 20 * (i - 1), startCol = 1)
    }
    add_toc("Poverty Measures (All Graphs)", "Plot_Measures_All")
  }

  if (!is.null(summary_list$poverty_distribution)) {
    indicators <- c("share_of_poor", "share_of_population")
    plots <- lapply(indicators, function(ind) plot_poverty_distribution(summary_list$poverty_distribution, indicator = ind))
    openxlsx::addWorksheet(wb, "Plot_Distribution_All")
    for (i in seq_along(plots)) {
      tmp <- tempfile(fileext = ".png")
      ggplot2::ggsave(tmp, plots[[i]], width = 8, height = 5)
      openxlsx::insertImage(wb, "Plot_Distribution_All", file = tmp, startRow = 1 + 20 * (i - 1), startCol = 1)
    }
    add_toc("Poverty Distribution (All Graphs)", "Plot_Distribution_All")
  }

  if (!is.null(summary_list$poverty_composition)) {
    indicators <- c("contribution_to_headcount", "contribution_to_gap", "contribution_to_severity")
    plots <- lapply(indicators, function(ind) plot_poverty_composition(summary_list$poverty_composition, indicator = ind))
    openxlsx::addWorksheet(wb, "Plot_Composition_All")
    for (i in seq_along(plots)) {
      tmp <- tempfile(fileext = ".png")
      ggplot2::ggsave(tmp, plots[[i]], width = 8, height = 5)
      openxlsx::insertImage(wb, "Plot_Composition_All", file = tmp, startRow = 1 + 20 * (i - 1), startCol = 1)
    }
    add_toc("Poverty Composition (All Graphs)", "Plot_Composition_All")
  }

  if (!is.null(transfer_results$table) && !is.null(transfer_results$plot_efficiency)) {
    openxlsx::addWorksheet(wb, "Transfer_Scenarios")
    openxlsx::writeData(wb, "Transfer_Scenarios", "Transfer Scenario Results", startRow = 1, startCol = 1)
    openxlsx::addStyle(wb, "Transfer_Scenarios",
                       openxlsx::createStyle(textDecoration = "bold", fontSize = 14),
                       rows = 1, cols = 1)
    openxlsx::writeDataTable(wb, "Transfer_Scenarios", transfer_results$table, startRow = 3)
    tmp <- tempfile(fileext = ".png")
    ggplot2::ggsave(tmp, transfer_results$plot_efficiency, width = 8, height = 5)
    openxlsx::insertImage(wb, "Transfer_Scenarios", tmp, startRow = 3, startCol = ncol(transfer_results$table) + 3, width = 6, height = 5, units = "in")
    add_toc("Transfer Scenarios (Table + Plot)", "Transfer_Scenarios")
  }

  if (!is.null(inequality_df)) {
    add_table_sheet("Inequality_Indices", inequality_df, "Gini & Theil Indices")
  }

  if (!is.null(lorenz_plots) && length(lorenz_plots) > 0) {
    openxlsx::addWorksheet(wb, "Lorenz_Curves")
    row_pos <- 1
    for (name in names(lorenz_plots)) {
      tmp <- tempfile(fileext = ".png")
      ggplot2::ggsave(tmp, lorenz_plots[[name]], width = 8, height = 5)
      openxlsx::insertImage(wb, "Lorenz_Curves", file = tmp, startRow = row_pos, startCol = 1, width = 7, height = 5, units = "in")
      row_pos <- row_pos + 25
    }
    add_toc("Lorenz Curves", "Lorenz_Curves")
  }

  openxlsx::writeData(wb, "Table_of_Contents", toc, startCol = 1, startRow = 1)
  for (i in seq_len(nrow(toc))) {
    openxlsx::writeFormula(wb, "Table_of_Contents",
                           x = openxlsx::makeHyperlinkString(toc$Sheet[i], row = 1, col = 1),
                           startRow = i + 1, startCol = 3)
  }

  openxlsx::saveWorkbook(wb, file, overwrite = TRUE)
  message("Report successfully exported: ", normalizePath(file))
}
